#!/usr/bin/env python

# Created on Tue Aug 21 19:53:19 2018
# Author: XiaoTao Wang

## Required modules

import argparse, sys, os, hicpeaks

currentVersion = hicpeaks.__version__

def getargs():
    ## Construct an ArgumentParser object for command-line arguments
    parser = argparse.ArgumentParser(description='''Visualize peak calls on heatmap.''',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    # Version
    parser.add_argument('-v', '--version', action='version',
                        version=' '.join(['%(prog)s',currentVersion]),
                        help='Print version number and exit.')
    
    # Output
    parser.add_argument('-O', '--output', help='Output png file name.')
    parser.add_argument('--dpi', default=200, type=int,
                        help='''The resolution in dots per inch of the output figure.''')

    # Input
    parser.add_argument('-p', '--path',
                        help = 'Cooler URI.')
    parser.add_argument('-I', '--loop-file', help='Loop file in bedpe format.')
    parser.add_argument('-C', '--chrom', help='Chromosome label of your anticipated region.')
    parser.add_argument('-S', '--start', type=int, help='Start site (bp) of the region.')
    parser.add_argument('-E', '--end', type=int, help='End site (bp) of the region.')
    parser.add_argument('--skip-rows', default=0, type=int,
                        help='''Number of leading lines in the loop file to skip.''')
    parser.add_argument('--balance-type', default='ICE', choices=['CNV', 'ICE', 'RAW'],
                        help='''Normalization type of the matrix.''')
    parser.add_argument('--log', action='store_true')
    parser.add_argument('--vmin', type=float,
                        help='''The minimum value that the colorbar covers.''')
    parser.add_argument('--vmax', type=float,
                        help='''The maximum value that the colorbar covers.''')
    parser.add_argument('--tick-num', type=int, default=2,
                        help='''Number of ticks for genomic coordinates''')
    parser.add_argument('--nolabel', action='store_true',
                        help='''Whether or not add genomic coordinates.''')
    
    ## Parse the command-line arguments
    commands = sys.argv[1:]
    if not commands:
        commands.append('-h')
    args = parser.parse_args(commands)
    
    return args, commands

def properU(pos):
    
    i_part = int(pos) // 1000000 # Integer Part
    d_part = (int(pos) % 1000000) // 1000 # Decimal Part
    
    if (i_part > 0) and (d_part > 0):
        return ''.join([str(i_part), 'M', str(d_part), 'K'])
    elif (i_part == 0):
        return ''.join([str(d_part), 'K'])
    else:
        return ''.join([str(i_part), 'M'])

def caxis_H(ax):
    """
    Axis Control for HeatMaps.
    """
    ax.yaxis.set_ticks_position('left')
    ax.xaxis.set_ticks_position('bottom')
    ax.tick_params(axis = 'both', labelsize = 12, length = 5, pad = 7)

def run():

    # Parse Arguments
    args, commands = getargs()
    # Improve the performance if you don't want to run it
    if commands[0] not in ['-h', '-v', '--help', '--version']:
        
        import numpy as np
        import matplotlib
        matplotlib.use('Agg')
        import cooler
        import matplotlib.pyplot as plt
        from matplotlib.colors import LinearSegmentedColormap
        from hicpeaks.utilities import _parse_peakfile
        from matplotlib.colors import LogNorm
        
        cmap = LinearSegmentedColormap.from_list('interaction',
                                                 ['#FFFFFF','#FFDFDF','#FF7575','#FF2626','#F70000'])
        #cmap.set_bad('#2672a1')
        cmap.set_bad('w')

        if args.balance_type == 'ICE':
            correct = 'weight'
        elif args.balance_type == 'CNV':
            correct = 'sweight'
        else:
            correct = False

        # Load Cooler
        Lib = cooler.Cooler(args.path)
        chrom, start, end = args.chrom, args.start, args.end

        # Extract matrix
        res = Lib.binsize
        start = start//res * res
        end = end//res * res
        M = Lib.matrix(balance=correct, sparse=False).fetch((chrom,start,end))
        M[np.isnan(M)] = 0
    
        nonzero = M[np.nonzero(M)]
        if args.vmin is None:
            vmin = nonzero.min()
        else:
            vmin = args.vmin
        if args.vmax is None:
            vmax = np.percentile(nonzero, 95)
        else:
            vmax = args.vmax

        chrom = chrom.lstrip('chr')
        Bool = np.zeros(M.shape, dtype=bool)
        if not args.loop_file is None:
            loop_file = args.loop_file
            # Read loop data
            loops = _parse_peakfile(loop_file, skip=args.skip_rows)
            loops = loops[chrom]
    
            # Mask original matrix using loop data
            for xs, xe, ys, ye in loops:
                # Lodate the peak pixel at given resolution
                s_l = range(xs//res, int(np.ceil(xe/float(res))))
                e_l = range(ys//res, int(np.ceil(ye/float(res))))
                si, ei = None, None
                for i in s_l:
                    for j in e_l:
                        st = i - start//res
                        et = j - start//res
                        if (0 <= st < M.shape[0]) and (0 <= et < M.shape[0]):
                            if si is None:
                                si, ei = st, et
                            else:
                                if M[st,et] > M[si,ei]:
                                    si, ei = st, et
                if not si is None:
                    if si < ei:
                        Bool[si, ei] = 1
                    else:
                        Bool[ei, si] = 1
    
        M = np.ma.array(M, mask = Bool)

        # Plot
        size = (8, 7.3)
        width = 0.7; Left = 0.1
        HB = 0.1; HH = width * size[0] / size[1]

        fig = plt.figure(figsize=size)
        ax = fig.add_axes([Left, HB, width, HH])
        if args.log:
            sc = ax.imshow(M, cmap = cmap, aspect = 'auto', interpolation = 'none',
                          norm=LogNorm(vmin=vmin, vmax=vmax))
        else:
            sc = ax.imshow(M, cmap = cmap, aspect = 'auto', interpolation = 'none',
                       vmax = vmax, vmin = vmin)
        if args.nolabel:
            ax.tick_params(axis='both', bottom=False, top=False, left=False, right=False,
                           labelbottom=False, labeltop=False, labelleft=False, labelright=False)
        else:
            interval = (end - start) // res
            ticks = list(np.linspace(0, interval, args.tick_num).astype(int))
            pos = list(np.linspace(start, end, args.tick_num).astype(int))
            labels = [properU(p) for p in pos]
            ax.set_xticks(ticks)
            ax.set_xticklabels(labels)
            ax.set_yticks(ticks)
            ax.set_yticklabels(labels)
            caxis_H(ax)

        ## Colorbar
        ax = fig.add_axes([Left+width+0.03, HB, 0.03, HH])
        fig.colorbar(sc, cax=ax)

        plt.savefig(args.output, bbox_inches='tight', dpi=args.dpi)
        plt.close()


if __name__ == '__main__':
    run()